### ISSUE TITLE
Lack of necessary documents

### ISSUE THREAD

**Issue by persistz** [AndyShih12/BNN_ODD#2]
Hi Andy,

After installing multiple torch packages, I can successfully start the 'run' scripts and  'gen_MNIST_data.lua' file.
But due to lack of data files, the script will throw out exceptions.

Could you provide the USPS datafiles which have been used in this repo?
Including but not limited to,

data/8x8/train/digit-0.data
data/8x8/train/digit-8.data
data/8x8/test/digit-0.data
data/8x8/test/digit-8.data

**Comment by AndyShih12** [comment]
Done! Check out the new files.
