### ISSUE TITLE
About OBDD size and number of assignments

### ISSUE THREAD

**Issue by zhangyedi** [AndyShih12/BNN_ODD#3]
Hi,
I have already run the code (./run_start) successfully. 

I have a question: how can I get the size of OBDD and the number of counter-examples (assignment satisfying the OBDD)? In fact, I have got files "**.obddas". Are these "solving" parts included in the current repo?

Thanks :-)

**Comment by AndyShih12** [comment]
The "solving" parts are not included in the current repository. You will need to use an OBDD package to query the model.

You could also convert the OBDD to an SDD (something like [this](https://github.com/AndyShih12/BNC_SDD/blob/master/src/oddtosdd.cpp)), and then use the [SDD package](http://reasoning.cs.ucla.edu/sdd/) to query the model. There are some examples of this [here](https://github.com/AndyShih12/STEP/blob/master/src/expl.py), but I am currently not maintaining these packages anymore.
